### ISSUE TITLE
issues running the app

### ISSUE THREAD

**Issue by jexp** [adadgio/neo4j-js-ng2#1]
ran npm start

```
> ng serve

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 29% building modules 166/195 modules 29 active ...es/rxjs/_esm5/operators/catchError.jswebpack: wait until bundle finished: /
Date: 2017-12-05T00:30:15.712Z                                                          
Hash: 4abc9cef81930038d1f0
Time: 16602ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 263 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 199 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 30.3 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.82 MB [initial] [rendered]

webpack: Compiled successfully.
```
![neo4jjs graph visualization and edition](https://user-images.githubusercontent.com/67427/33583769-3e38bd70-d95c-11e7-929a-acb34aeb64f2.jpg)

**Comment by adadgio** [comment]
Looks like an issue in the settings service. Did you rename `src/assets/neo4j.settings.json.dist` into  `src/assets/neo4j.settings.json` ? (I juste updated the default settings file, please pull latest `develop` / `master` version)

1. Also don't forget to do a proper `npm install` before running the app.
2. Which angular2 CLI version and Typescript version are you running ?

**Comment by jexp** [comment]
I did just npm install in the repo.

And yes I renamed the settings file:
```
file src/assets/neo4j.settings.json
src/assets/neo4j.settings.json: ASCII text
```

**Comment by adadgio** [comment]
Hmm, I can't reproduce the issue, i retested a brand new clone/install from the repo, which works. It might be more related to Angular2 CLI in my opinion. I can't see the **very beginning** of the error in your console though. Could you show us that ?
