### ISSUE TITLE
Unable to reproduce basic functionalities

### ISSUE THREAD

**Issue by pedroig** [adadgio/neo4j-js-ng2#13]
I am facing many bugs with a simple reproduction of the application. Here is a list of the main bugs:
* At most one node is shown after a simple query or a cypher query;
![Error gif 01](https://cdn.pbrd.co/images/HRyQ6Dt.gif)
* The same bug also happens when in creation mode;
![Error gif 02](https://cdn.pbrd.co/images/HRyUkCY.gif)
* Unable to query a number as string using the simple query;
![Error gif 03](https://cdn.pbrd.co/images/HRyWNyB.gif)
* Unable to visualize or edit any relationship;
* Unable to use simple queries that show the 1st level relationships  with +1 flag. Example:
`:Knowledge name="Bases" +1` generates the following cypher query in the logs (which is not valid): `"MATCH (a:Knowledge) WHERE a.name='Bases'-[r]->(b) RETURN a, b, r, ID(a), ID(b), TYPE(r), LABELS(a), LABELS(b) LIMIT 1\"`.

Any thoughts on why those errors are happening? Is there a restriction for the neo4j version used? I am using neo4j-3.5.0

**Comment by adadgio** [comment]
Any update on this ? I couldnt find any problem, and images are not working on your issue...
