### ISSUE TITLE
It would be good to infer human readable captions automatically

### ISSUE THREAD

**Issue by jexp** [adadgio/neo4j-js-ng2#6]
In Neo4j browser we do it with:

per node, if it has a property that case-insensitive equals: name, title, label
or ends with name, title,label
In that order then we use it as caption.

It would also be nice to be able to style nodes visually like in Neo4j Browser.

**Comment by adadgio** [comment]
Captions are configured and configurable in the settings, on the fly as well (see settings link in the header!)
