### ISSUE TITLE
ctrl-c is not  a good keyboard shortcut b/c it conflicts with "copy" on Windows / Linux

### ISSUE THREAD

**Issue by jexp** [adadgio/neo4j-js-ng2#9]

**Comment by adadgio** [comment]
This is fixed a [this commit](https://github.com/adadgio/neo4j-js-ng2/commit/da3eda17274951ce4b625dc68ae733222a90fe43). The default key now is CTRL+N (for new), and take has been taken to make this fully customizable in json settings.
